# Generated by Django 3.1.1 on 2020-09-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processimage',
            name='palette',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
