# Generated by Django 3.1.1 on 2020-09-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20200903_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processimage',
            old_name='process_Main_Img',
            new_name='Choose_Image',
        ),
    ]
